---

name:
    wolfram
version:
    0.1.0.0
github:
    matheograil/wolfram
homepage:
    https://github.com/matheograil/wolfram#readme
license:
    BSD3
author:
    Mathéo Grail
maintainer:
    grail.matheo@protonmail.com
copyright:
    2023 Mathéo Grail
category:
    Studies


synopsis:
    The goal of this project is to implement Wolfram’s elementary cellular automaton in the terminal.

description: |
    The goal of this project is to implement Wolfram’s elementary cellular automaton in the terminal.
    https://en.wikipedia.org/wiki/Elementary_cellular_automaton
    You only have to implement rule 30, rule 90 and rule 110. The other rules are considered a bonus.
    The space your cellular automaton are living in is infinite (to the left, right, and bottom). This means the parts not shown on screen can still have an effect on future generations.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        []

executables:
    wolfram:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - wolfram

tests:
    wolfram-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - wolfram
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
